export type Finger = 0 | 1 | 2 | 3 | 4;

export type KeyWidth = "wide" | "extra-wide" | "spacebar";

export interface KeyData {
  display: string;
  displayShift?: string;
  value: string;
  finger: Finger;
  width?: KeyWidth;
  grow?: boolean;
}

export const KEYBOARD_LAYOUTS: Record<string, KeyData[][]> = {
  qwerty: [
    [
      { display: "`", displayShift: "~", value: "`", finger: 0 },
      { display: "1", displayShift: "!", value: "1", finger: 0 },
      { display: "2", displayShift: "@", value: "2", finger: 1 },
      { display: "3", displayShift: "#", value: "3", finger: 2 },
      { display: "4", displayShift: "$", value: "4", finger: 3 },
      { display: "5", displayShift: "%", value: "5", finger: 3 },
      { display: "6", displayShift: "^", value: "6", finger: 3 },
      { display: "7", displayShift: "&", value: "7", finger: 3 },
      { display: "8", displayShift: "*", value: "8", finger: 2 },
      { display: "9", displayShift: "(", value: "9", finger: 1 },
      { display: "0", displayShift: ")", value: "0", finger: 0 },
      { display: "-", displayShift: "_", value: "-", finger: 0 },
      { display: "=", displayShift: "+", value: "=", finger: 0 },
      { display: "Backspace", value: "backspace", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Tab", value: "tab", finger: 0, width: "wide" },
      { display: "Q", value: "q", finger: 0 },
      { display: "W", value: "w", finger: 1 },
      { display: "E", value: "e", finger: 2 },
      { display: "R", value: "r", finger: 3 },
      { display: "T", value: "t", finger: 3 },
      { display: "Y", value: "y", finger: 3 },
      { display: "U", value: "u", finger: 3 },
      { display: "I", value: "i", finger: 2 },
      { display: "O", value: "o", finger: 1 },
      { display: "P", value: "p", finger: 0 },
      { display: "[", displayShift: "{", value: "[", finger: 0 },
      { display: "]", displayShift: "}", value: "]", finger: 0 },
      { display: "\\", displayShift: "|", value: "\\", finger: 0, width: "wide" },
    ],
    [
      { display: "Caps", value: "capslock", finger: 0, width: "wide" },
      { display: "A", value: "a", finger: 0 },
      { display: "S", value: "s", finger: 1 },
      { display: "D", value: "d", finger: 2 },
      { display: "F", value: "f", finger: 3 },
      { display: "G", value: "g", finger: 3 },
      { display: "H", value: "h", finger: 3 },
      { display: "J", value: "j", finger: 3 },
      { display: "K", value: "k", finger: 2 },
      { display: "L", value: "l", finger: 1 },
      { display: ";", displayShift: ":", value: ";", finger: 0 },
      { display: "'", displayShift: '"', value: "'", finger: 0 },
      { display: "Enter", value: "enter", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Shift", value: "shift", finger: 0, width: "wide" },
      { display: "Z", value: "z", finger: 0 },
      { display: "X", value: "x", finger: 1 },
      { display: "C", value: "c", finger: 2 },
      { display: "V", value: "v", finger: 3 },
      { display: "B", value: "b", finger: 3 },
      { display: "N", value: "n", finger: 3 },
      { display: "M", value: "m", finger: 3 },
      { display: ",", displayShift: "<", value: ",", finger: 2 },
      { display: ".", displayShift: ">", value: ".", finger: 1 },
      { display: "/", displayShift: "?", value: "/", finger: 0 },
      { display: "Shift", value: "shift", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Ctrl", value: "control", finger: 0, grow: true },
      { display: "Alt", value: "alt", finger: 0, grow: true },
      { display: "Space", value: " ", finger: 4, width: "spacebar" },
      { display: "Alt", value: "alt", finger: 0, grow: true },
      { display: "Ctrl", value: "control", finger: 0, grow: true },
    ],
  ],
  dvorak: [
    [
      { display: "`", displayShift: "~", value: "`", finger: 0 },
      { display: "1", displayShift: "!", value: "1", finger: 0 },
      { display: "2", displayShift: "@", value: "2", finger: 1 },
      { display: "3", displayShift: "#", value: "3", finger: 2 },
      { display: "4", displayShift: "$", value: "4", finger: 3 },
      { display: "5", displayShift: "%", value: "5", finger: 3 },
      { display: "6", displayShift: "^", value: "6", finger: 3 },
      { display: "7", displayShift: "&", value: "7", finger: 3 },
      { display: "8", displayShift: "*", value: "8", finger: 2 },
      { display: "9", displayShift: "(", value: "9", finger: 1 },
      { display: "0", displayShift: ")", value: "0", finger: 0 },
      { display: "-", displayShift: "_", value: "-", finger: 0 },
      { display: "=", displayShift: "+", value: "=", finger: 0 },
      { display: "Backspace", value: "backspace", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Tab", value: "tab", finger: 0, width: "wide" },
      { display: "'", displayShift: '"', value: "'", finger: 0 },
      { display: ",", displayShift: "<", value: ",", finger: 1 },
      { display: ".", displayShift: ">", value: ".", finger: 2 },
      { display: "P", value: "p", finger: 3 },
      { display: "Y", value: "y", finger: 3 },
      { display: "F", value: "f", finger: 3 },
      { display: "G", value: "g", finger: 3 },
      { display: "C", value: "c", finger: 2 },
      { display: "R", value: "r", finger: 1 },
      { display: "L", value: "l", finger: 0 },
      { display: "/", displayShift: "?", value: "/", finger: 0 },
      { display: "=", displayShift: "+", value: "=", finger: 0 },
      { display: "\\", displayShift: "|", value: "\\", finger: 0, width: "wide" },
    ],
    [
      { display: "Caps", value: "capslock", finger: 0, width: "wide" },
      { display: "A", value: "a", finger: 0 },
      { display: "O", value: "o", finger: 1 },
      { display: "E", value: "e", finger: 2 },
      { display: "U", value: "u", finger: 3 },
      { display: "I", value: "i", finger: 3 },
      { display: "D", value: "d", finger: 3 },
      { display: "H", value: "h", finger: 3 },
      { display: "T", value: "t", finger: 2 },
      { display: "N", value: "n", finger: 1 },
      { display: "S", value: "s", finger: 0 },
      { display: "-", displayShift: "_", value: "-", finger: 0 },
      { display: "Enter", value: "enter", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Shift", value: "shift", finger: 0, width: "wide" },
      { display: ";", displayShift: ":", value: ";", finger: 0 },
      { display: "Q", value: "q", finger: 1 },
      { display: "J", value: "j", finger: 2 },
      { display: "K", value: "k", finger: 3 },
      { display: "X", value: "x", finger: 3 },
      { display: "B", value: "b", finger: 3 },
      { display: "M", value: "m", finger: 3 },
      { display: "W", value: "w", finger: 2 },
      { display: "V", value: "v", finger: 1 },
      { display: "Z", value: "z", finger: 0 },
      { display: "Shift", value: "shift", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Ctrl", value: "control", finger: 0, grow: true },
      { display: "Alt", value: "alt", finger: 0, grow: true },
      { display: "Space", value: " ", finger: 4, width: "spacebar" },
      { display: "Alt", value: "alt", finger: 0, grow: true },
      { display: "Ctrl", value: "control", finger: 0, grow: true },
    ],
  ],
  colemak: [
    [
      { display: "`", displayShift: "~", value: "`", finger: 0 },
      { display: "1", displayShift: "!", value: "1", finger: 0 },
      { display: "2", displayShift: "@", value: "2", finger: 1 },
      { display: "3", displayShift: "#", value: "3", finger: 2 },
      { display: "4", displayShift: "$", value: "4", finger: 3 },
      { display: "5", displayShift: "%", value: "5", finger: 3 },
      { display: "6", displayShift: "^", value: "6", finger: 3 },
      { display: "7", displayShift: "&", value: "7", finger: 3 },
      { display: "8", displayShift: "*", value: "8", finger: 2 },
      { display: "9", displayShift: "(", value: "9", finger: 1 },
      { display: "0", displayShift: ")", value: "0", finger: 0 },
      { display: "-", displayShift: "_", value: "-", finger: 0 },
      { display: "=", displayShift: "+", value: "=", finger: 0 },
      { display: "Backspace", value: "backspace", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Tab", value: "tab", finger: 0, width: "wide" },
      { display: "Q", value: "q", finger: 0 },
      { display: "W", value: "w", finger: 1 },
      { display: "F", value: "f", finger: 2 },
      { display: "P", value: "p", finger: 3 },
      { display: "G", value: "g", finger: 3 },
      { display: "J", value: "j", finger: 3 },
      { display: "L", value: "l", finger: 3 },
      { display: "U", value: "u", finger: 2 },
      { display: "Y", value: "y", finger: 1 },
      { display: ";", displayShift: ":", value: ";", finger: 0 },
      { display: "[", displayShift: "{", value: "[", finger: 0 },
      { display: "]", displayShift: "}", value: "]", finger: 0 },
      { display: "\\", displayShift: "|", value: "\\", finger: 0, width: "wide" },
    ],
    [
      { display: "Caps", value: "capslock", finger: 0, width: "wide" },
      { display: "A", value: "a", finger: 0 },
      { display: "R", value: "r", finger: 1 },
      { display: "S", value: "s", finger: 2 },
      { display: "T", value: "t", finger: 3 },
      { display: "D", value: "d", finger: 3 },
      { display: "H", value: "h", finger: 3 },
      { display: "N", value: "n", finger: 3 },
      { display: "E", value: "e", finger: 2 },
      { display: "I", value: "i", finger: 1 },
      { display: "O", value: "o", finger: 0 },
      { display: "'", displayShift: '"', value: "'", finger: 0 },
      { display: "Enter", value: "enter", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Shift", value: "shift", finger: 0, width: "wide" },
      { display: "Z", value: "z", finger: 0 },
      { display: "X", value: "x", finger: 1 },
      { display: "C", value: "c", finger: 2 },
      { display: "V", value: "v", finger: 3 },
      { display: "B", value: "b", finger: 3 },
      { display: "K", value: "k", finger: 3 },
      { display: "M", value: "m", finger: 3 },
      { display: ",", displayShift: "<", value: ",", finger: 2 },
      { display: ".", displayShift: ">", value: ".", finger: 1 },
      { display: "/", displayShift: "?", value: "/", finger: 0 },
      { display: "Shift", value: "shift", finger: 0, width: "extra-wide" },
    ],
    [
      { display: "Ctrl", value: "control", finger: 0, grow: true },
      { display: "Alt", value: "alt", finger: 0, grow: true },
      { display: "Space", value: " ", finger: 4, width: "spacebar" },
      { display: "Alt", value: "alt", finger: 0, grow: true },
      { display: "Ctrl", value: "control", finger: 0, grow: true },
    ],
  ],
};